# Generated by Django 4.2.7 on 2023-11-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='fam',
            field=models.TextField(max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.TextField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='otc',
            field=models.TextField(max_length=64, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.TextField(max_length=64, verbose_name='Контактный телефон'),
        ),
    ]
